[2022-03-14 20:29:45,051] {processor.py:163} INFO - Started process (PID=6103) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:29:45,052] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:29:45,052] {logging_mixin.py:109} INFO - [2022-03-14 20:29:45,052] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:29:45,568] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:29:46,281] {logging_mixin.py:109} INFO - [2022-03-14 20:29:46,281] {manager.py:496} INFO - Created Permission View: can edit on DAG:gcs_ingestion_dag_v02
[2022-03-14 20:29:46,285] {logging_mixin.py:109} INFO - [2022-03-14 20:29:46,285] {manager.py:496} INFO - Created Permission View: can read on DAG:gcs_ingestion_dag_v02
[2022-03-14 20:29:46,286] {logging_mixin.py:109} INFO - [2022-03-14 20:29:46,285] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:29:46,289] {logging_mixin.py:109} INFO - [2022-03-14 20:29:46,289] {dag.py:2415} INFO - Creating ORM DAG for gcs_ingestion_dag_v02
[2022-03-14 20:29:46,294] {logging_mixin.py:109} INFO - [2022-03-14 20:29:46,294] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-01-01T00:00:00+00:00
[2022-03-14 20:29:46,300] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 1.252 seconds
[2022-03-14 20:30:16,417] {processor.py:163} INFO - Started process (PID=6166) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:16,419] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:30:16,419] {logging_mixin.py:109} INFO - [2022-03-14 20:30:16,419] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:16,905] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:16,911] {logging_mixin.py:109} INFO - [2022-03-14 20:30:16,911] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:30:16,922] {logging_mixin.py:109} INFO - [2022-03-14 20:30:16,922] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-01-01T00:00:00+00:00
[2022-03-14 20:30:16,929] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.514 seconds
[2022-03-14 20:30:47,035] {processor.py:163} INFO - Started process (PID=6227) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:47,036] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:30:47,036] {logging_mixin.py:109} INFO - [2022-03-14 20:30:47,036] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:47,522] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:30:47,528] {logging_mixin.py:109} INFO - [2022-03-14 20:30:47,528] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:30:47,540] {logging_mixin.py:109} INFO - [2022-03-14 20:30:47,540] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-01-01T00:00:00+00:00
[2022-03-14 20:30:47,547] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.513 seconds
[2022-03-14 20:31:17,630] {processor.py:163} INFO - Started process (PID=6279) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:17,639] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:31:17,639] {logging_mixin.py:109} INFO - [2022-03-14 20:31:17,639] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:18,097] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:18,102] {logging_mixin.py:109} INFO - [2022-03-14 20:31:18,102] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:31:18,113] {logging_mixin.py:109} INFO - [2022-03-14 20:31:18,113] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-01-01T00:00:00+00:00
[2022-03-14 20:31:18,119] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.491 seconds
[2022-03-14 20:31:48,207] {processor.py:163} INFO - Started process (PID=6340) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:48,209] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:31:48,209] {logging_mixin.py:109} INFO - [2022-03-14 20:31:48,209] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:48,646] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:31:48,652] {logging_mixin.py:109} INFO - [2022-03-14 20:31:48,651] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:31:48,662] {logging_mixin.py:109} INFO - [2022-03-14 20:31:48,662] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-01-01T00:00:00+00:00
[2022-03-14 20:31:48,668] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.462 seconds
[2022-03-14 20:32:18,744] {processor.py:163} INFO - Started process (PID=6402) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:18,745] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:32:18,746] {logging_mixin.py:109} INFO - [2022-03-14 20:32:18,746] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:19,221] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:19,227] {logging_mixin.py:109} INFO - [2022-03-14 20:32:19,227] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:32:19,242] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.500 seconds
[2022-03-14 20:32:49,320] {processor.py:163} INFO - Started process (PID=6455) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:49,320] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:32:49,321] {logging_mixin.py:109} INFO - [2022-03-14 20:32:49,321] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:49,783] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:32:49,788] {logging_mixin.py:109} INFO - [2022-03-14 20:32:49,788] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:32:49,803] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.485 seconds
[2022-03-14 20:33:19,878] {processor.py:163} INFO - Started process (PID=6518) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:19,879] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:33:19,879] {logging_mixin.py:109} INFO - [2022-03-14 20:33:19,879] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:20,348] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:20,353] {logging_mixin.py:109} INFO - [2022-03-14 20:33:20,353] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:33:20,369] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.493 seconds
[2022-03-14 20:33:50,486] {processor.py:163} INFO - Started process (PID=6570) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:50,488] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:33:50,488] {logging_mixin.py:109} INFO - [2022-03-14 20:33:50,488] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:50,987] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:33:50,993] {logging_mixin.py:109} INFO - [2022-03-14 20:33:50,992] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:33:51,008] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.524 seconds
[2022-03-14 20:34:21,119] {processor.py:163} INFO - Started process (PID=6632) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:21,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:34:21,121] {logging_mixin.py:109} INFO - [2022-03-14 20:34:21,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:21,648] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:21,655] {logging_mixin.py:109} INFO - [2022-03-14 20:34:21,655] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:34:21,674] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.557 seconds
[2022-03-14 20:34:51,773] {processor.py:163} INFO - Started process (PID=6696) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:51,775] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:34:51,775] {logging_mixin.py:109} INFO - [2022-03-14 20:34:51,775] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:52,245] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:34:52,251] {logging_mixin.py:109} INFO - [2022-03-14 20:34:52,251] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:34:52,267] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.496 seconds
[2022-03-14 20:35:22,349] {processor.py:163} INFO - Started process (PID=6748) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:22,358] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:35:22,358] {logging_mixin.py:109} INFO - [2022-03-14 20:35:22,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:22,812] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:22,818] {logging_mixin.py:109} INFO - [2022-03-14 20:35:22,818] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:35:22,833] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.486 seconds
[2022-03-14 20:35:52,910] {processor.py:163} INFO - Started process (PID=6811) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:52,919] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:35:52,919] {logging_mixin.py:109} INFO - [2022-03-14 20:35:52,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:53,392] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:35:53,398] {logging_mixin.py:109} INFO - [2022-03-14 20:35:53,398] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:35:53,413] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.505 seconds
[2022-03-14 20:36:23,485] {processor.py:163} INFO - Started process (PID=6873) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:23,486] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:36:23,486] {logging_mixin.py:109} INFO - [2022-03-14 20:36:23,486] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:24,010] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:24,015] {logging_mixin.py:109} INFO - [2022-03-14 20:36:24,015] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:36:24,031] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.548 seconds
[2022-03-14 20:36:54,122] {processor.py:163} INFO - Started process (PID=6925) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:54,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:36:54,124] {logging_mixin.py:109} INFO - [2022-03-14 20:36:54,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:54,593] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:36:54,599] {logging_mixin.py:109} INFO - [2022-03-14 20:36:54,599] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:36:54,616] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.496 seconds
[2022-03-14 20:37:24,701] {processor.py:163} INFO - Started process (PID=6987) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:24,703] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:37:24,703] {logging_mixin.py:109} INFO - [2022-03-14 20:37:24,703] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:25,162] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:25,168] {logging_mixin.py:109} INFO - [2022-03-14 20:37:25,168] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:37:25,184] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.485 seconds
[2022-03-14 20:37:55,299] {processor.py:163} INFO - Started process (PID=7039) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:55,301] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:37:55,301] {logging_mixin.py:109} INFO - [2022-03-14 20:37:55,301] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:55,832] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:37:55,838] {logging_mixin.py:109} INFO - [2022-03-14 20:37:55,838] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:37:55,855] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.558 seconds
[2022-03-14 20:38:25,938] {processor.py:163} INFO - Started process (PID=7102) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:25,940] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:38:25,940] {logging_mixin.py:109} INFO - [2022-03-14 20:38:25,940] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:26,397] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:26,403] {logging_mixin.py:109} INFO - [2022-03-14 20:38:26,402] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:38:26,420] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.484 seconds
[2022-03-14 20:38:56,529] {processor.py:163} INFO - Started process (PID=7165) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:56,538] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:38:56,538] {logging_mixin.py:109} INFO - [2022-03-14 20:38:56,538] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:57,031] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:38:57,038] {logging_mixin.py:109} INFO - [2022-03-14 20:38:57,038] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:38:57,059] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.531 seconds
[2022-03-14 20:39:27,154] {processor.py:163} INFO - Started process (PID=7217) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:27,155] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:39:27,156] {logging_mixin.py:109} INFO - [2022-03-14 20:39:27,156] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:27,698] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:27,703] {logging_mixin.py:109} INFO - [2022-03-14 20:39:27,703] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:39:27,719] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.567 seconds
[2022-03-14 20:39:57,819] {processor.py:163} INFO - Started process (PID=7279) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:57,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:39:57,821] {logging_mixin.py:109} INFO - [2022-03-14 20:39:57,821] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:58,277] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:39:58,284] {logging_mixin.py:109} INFO - [2022-03-14 20:39:58,284] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:39:58,298] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.481 seconds
[2022-03-14 20:40:28,397] {processor.py:163} INFO - Started process (PID=7341) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:28,399] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:40:28,399] {logging_mixin.py:109} INFO - [2022-03-14 20:40:28,399] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:28,849] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:28,855] {logging_mixin.py:109} INFO - [2022-03-14 20:40:28,855] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:40:28,871] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.475 seconds
[2022-03-14 20:40:58,980] {processor.py:163} INFO - Started process (PID=7393) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:58,981] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:40:58,982] {logging_mixin.py:109} INFO - [2022-03-14 20:40:58,982] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:59,452] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:40:59,458] {logging_mixin.py:109} INFO - [2022-03-14 20:40:59,458] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:40:59,474] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.496 seconds
[2022-03-14 20:41:29,569] {processor.py:163} INFO - Started process (PID=7456) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:41:29,578] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:41:29,578] {logging_mixin.py:109} INFO - [2022-03-14 20:41:29,578] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:41:30,041] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:41:30,046] {logging_mixin.py:109} INFO - [2022-03-14 20:41:30,046] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:41:30,062] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.495 seconds
[2022-03-14 20:42:00,136] {processor.py:163} INFO - Started process (PID=7519) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:00,144] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:42:00,145] {logging_mixin.py:109} INFO - [2022-03-14 20:42:00,145] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:00,654] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:00,659] {logging_mixin.py:109} INFO - [2022-03-14 20:42:00,659] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:42:00,675] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.541 seconds
[2022-03-14 20:42:30,752] {processor.py:163} INFO - Started process (PID=7571) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:30,753] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:42:30,753] {logging_mixin.py:109} INFO - [2022-03-14 20:42:30,753] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:31,220] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:42:31,225] {logging_mixin.py:109} INFO - [2022-03-14 20:42:31,225] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:42:31,239] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.488 seconds
[2022-03-14 20:43:01,318] {processor.py:163} INFO - Started process (PID=7634) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:01,319] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:43:01,319] {logging_mixin.py:109} INFO - [2022-03-14 20:43:01,319] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:01,784] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:01,789] {logging_mixin.py:109} INFO - [2022-03-14 20:43:01,789] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:43:01,800] {logging_mixin.py:109} INFO - [2022-03-14 20:43:01,800] {dag.py:2935} INFO - Setting next_dagrun for gcs_ingestion_dag_v02 to 2020-02-01T00:00:00+00:00
[2022-03-14 20:43:01,806] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.490 seconds
[2022-03-14 20:43:31,923] {processor.py:163} INFO - Started process (PID=7696) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:31,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:43:31,926] {logging_mixin.py:109} INFO - [2022-03-14 20:43:31,925] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:32,475] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:43:32,480] {logging_mixin.py:109} INFO - [2022-03-14 20:43:32,480] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:43:32,496] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.575 seconds
[2022-03-14 20:44:02,607] {processor.py:163} INFO - Started process (PID=7748) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:02,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:44:02,608] {logging_mixin.py:109} INFO - [2022-03-14 20:44:02,607] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:03,087] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:03,093] {logging_mixin.py:109} INFO - [2022-03-14 20:44:03,093] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:44:03,109] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.504 seconds
[2022-03-14 20:44:33,195] {processor.py:163} INFO - Started process (PID=7811) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:33,203] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:44:33,204] {logging_mixin.py:109} INFO - [2022-03-14 20:44:33,204] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:33,665] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:44:33,671] {logging_mixin.py:109} INFO - [2022-03-14 20:44:33,671] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:44:33,687] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.494 seconds
[2022-03-14 20:45:03,764] {processor.py:163} INFO - Started process (PID=7864) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:03,772] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:45:03,773] {logging_mixin.py:109} INFO - [2022-03-14 20:45:03,773] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:04,243] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:04,248] {logging_mixin.py:109} INFO - [2022-03-14 20:45:04,247] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:45:04,261] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.499 seconds
[2022-03-14 20:45:34,338] {processor.py:163} INFO - Started process (PID=7926) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:34,346] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:45:34,347] {logging_mixin.py:109} INFO - [2022-03-14 20:45:34,347] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:34,823] {processor.py:654} INFO - DAG(s) dict_keys(['gcs_ingestion_dag_v02']) retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:34,828] {logging_mixin.py:109} INFO - [2022-03-14 20:45:34,828] {dag.py:2396} INFO - Sync 1 DAGs
[2022-03-14 20:45:34,844] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.508 seconds
[2022-03-14 20:45:36,354] {processor.py:163} INFO - Started process (PID=7943) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:36,356] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:45:36,356] {logging_mixin.py:109} INFO - [2022-03-14 20:45:36,356] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:36,868] {logging_mixin.py:109} INFO - [2022-03-14 20:45:36,868] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:45:36,877] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:36,877] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:45:36,882] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.530 seconds
[2022-03-14 20:46:06,976] {processor.py:163} INFO - Started process (PID=8006) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:06,977] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:46:06,977] {logging_mixin.py:109} INFO - [2022-03-14 20:46:06,977] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:07,460] {logging_mixin.py:109} INFO - [2022-03-14 20:46:07,459] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:46:07,468] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:07,473] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.499 seconds
[2022-03-14 20:46:37,556] {processor.py:163} INFO - Started process (PID=8059) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:37,558] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:46:37,558] {logging_mixin.py:109} INFO - [2022-03-14 20:46:37,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:38,077] {logging_mixin.py:109} INFO - [2022-03-14 20:46:38,076] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:46:38,085] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:46:38,090] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.536 seconds
[2022-03-14 20:47:08,171] {processor.py:163} INFO - Started process (PID=8121) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:08,173] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:47:08,173] {logging_mixin.py:109} INFO - [2022-03-14 20:47:08,173] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:08,682] {logging_mixin.py:109} INFO - [2022-03-14 20:47:08,681] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:47:08,690] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:08,696] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.526 seconds
[2022-03-14 20:47:38,807] {processor.py:163} INFO - Started process (PID=8183) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:38,809] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:47:38,809] {logging_mixin.py:109} INFO - [2022-03-14 20:47:38,809] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:39,266] {logging_mixin.py:109} INFO - [2022-03-14 20:47:39,265] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:47:39,274] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:47:39,279] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.475 seconds
[2022-03-14 20:48:09,362] {processor.py:163} INFO - Started process (PID=8236) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:09,364] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:48:09,364] {logging_mixin.py:109} INFO - [2022-03-14 20:48:09,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:09,832] {logging_mixin.py:109} INFO - [2022-03-14 20:48:09,831] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:48:09,839] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:09,844] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.484 seconds
[2022-03-14 20:48:39,938] {processor.py:163} INFO - Started process (PID=8298) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:39,939] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:48:39,940] {logging_mixin.py:109} INFO - [2022-03-14 20:48:39,940] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:40,405] {logging_mixin.py:109} INFO - [2022-03-14 20:48:40,405] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:48:40,413] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:48:40,419] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.483 seconds
[2022-03-14 20:49:10,550] {processor.py:163} INFO - Started process (PID=8360) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:10,551] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:49:10,552] {logging_mixin.py:109} INFO - [2022-03-14 20:49:10,552] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:11,009] {logging_mixin.py:109} INFO - [2022-03-14 20:49:11,008] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:49:11,017] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:11,022] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.474 seconds
[2022-03-14 20:49:41,099] {processor.py:163} INFO - Started process (PID=8412) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:41,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:49:41,108] {logging_mixin.py:109} INFO - [2022-03-14 20:49:41,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:41,581] {logging_mixin.py:109} INFO - [2022-03-14 20:49:41,580] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:49:41,589] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:49:41,595] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.497 seconds
[2022-03-14 20:50:11,681] {processor.py:163} INFO - Started process (PID=8474) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:11,682] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:50:11,682] {logging_mixin.py:109} INFO - [2022-03-14 20:50:11,682] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:12,155] {logging_mixin.py:109} INFO - [2022-03-14 20:50:12,155] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:50:12,165] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:12,171] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.492 seconds
[2022-03-14 20:50:42,792] {processor.py:163} INFO - Started process (PID=8537) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:42,794] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:50:42,794] {logging_mixin.py:109} INFO - [2022-03-14 20:50:42,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:43,322] {logging_mixin.py:109} INFO - [2022-03-14 20:50:43,321] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:50:43,330] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:50:43,336] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.546 seconds
[2022-03-14 20:51:13,459] {processor.py:163} INFO - Started process (PID=8590) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:13,461] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:51:13,461] {logging_mixin.py:109} INFO - [2022-03-14 20:51:13,461] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:13,964] {logging_mixin.py:109} INFO - [2022-03-14 20:51:13,964] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:51:13,973] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:13,978] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.520 seconds
[2022-03-14 20:51:44,079] {processor.py:163} INFO - Started process (PID=8651) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:44,080] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:51:44,080] {logging_mixin.py:109} INFO - [2022-03-14 20:51:44,080] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:44,578] {logging_mixin.py:109} INFO - [2022-03-14 20:51:44,578] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:51:44,587] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:51:44,593] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.516 seconds
[2022-03-14 20:52:14,692] {processor.py:163} INFO - Started process (PID=8704) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:14,694] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:52:14,694] {logging_mixin.py:109} INFO - [2022-03-14 20:52:14,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:15,198] {logging_mixin.py:109} INFO - [2022-03-14 20:52:15,197] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:52:15,206] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:15,212] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.522 seconds
[2022-03-14 20:52:45,322] {processor.py:163} INFO - Started process (PID=8766) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:45,324] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:52:45,324] {logging_mixin.py:109} INFO - [2022-03-14 20:52:45,324] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:45,835] {logging_mixin.py:109} INFO - [2022-03-14 20:52:45,834] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:52:45,843] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:52:45,848] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.528 seconds
[2022-03-14 20:53:15,942] {processor.py:163} INFO - Started process (PID=8828) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:15,943] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:53:15,944] {logging_mixin.py:109} INFO - [2022-03-14 20:53:15,944] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:16,377] {logging_mixin.py:109} INFO - [2022-03-14 20:53:16,377] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:53:16,384] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:16,389] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.449 seconds
[2022-03-14 20:53:46,487] {processor.py:163} INFO - Started process (PID=8880) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:46,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:53:46,489] {logging_mixin.py:109} INFO - [2022-03-14 20:53:46,489] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:46,944] {logging_mixin.py:109} INFO - [2022-03-14 20:53:46,944] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:53:46,952] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:53:46,957] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.472 seconds
[2022-03-14 20:54:17,066] {processor.py:163} INFO - Started process (PID=8942) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:17,066] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:54:17,066] {logging_mixin.py:109} INFO - [2022-03-14 20:54:17,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:17,526] {logging_mixin.py:109} INFO - [2022-03-14 20:54:17,526] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:54:17,534] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:17,540] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.476 seconds
[2022-03-14 20:54:47,629] {processor.py:163} INFO - Started process (PID=9004) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:47,630] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:54:47,630] {logging_mixin.py:109} INFO - [2022-03-14 20:54:47,630] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:48,076] {logging_mixin.py:109} INFO - [2022-03-14 20:54:48,075] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:54:48,084] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:54:48,090] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.462 seconds
[2022-03-14 20:55:18,188] {processor.py:163} INFO - Started process (PID=9056) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:18,188] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:55:18,189] {logging_mixin.py:109} INFO - [2022-03-14 20:55:18,189] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:18,651] {logging_mixin.py:109} INFO - [2022-03-14 20:55:18,651] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:55:18,659] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:18,665] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.479 seconds
[2022-03-14 20:55:48,785] {processor.py:163} INFO - Started process (PID=9117) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:48,788] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:55:48,789] {logging_mixin.py:109} INFO - [2022-03-14 20:55:48,789] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:49,256] {logging_mixin.py:109} INFO - [2022-03-14 20:55:49,255] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:55:49,264] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:55:49,269] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.491 seconds
[2022-03-14 20:56:19,383] {processor.py:163} INFO - Started process (PID=9171) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:19,385] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:56:19,385] {logging_mixin.py:109} INFO - [2022-03-14 20:56:19,385] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:19,849] {logging_mixin.py:109} INFO - [2022-03-14 20:56:19,848] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:56:19,857] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:19,863] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.481 seconds
[2022-03-14 20:56:49,970] {processor.py:163} INFO - Started process (PID=9233) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:49,970] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:56:49,971] {logging_mixin.py:109} INFO - [2022-03-14 20:56:49,970] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:50,422] {logging_mixin.py:109} INFO - [2022-03-14 20:56:50,421] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:56:50,430] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:56:50,436] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.468 seconds
[2022-03-14 20:57:20,526] {processor.py:163} INFO - Started process (PID=9294) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:20,528] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:57:20,528] {logging_mixin.py:109} INFO - [2022-03-14 20:57:20,528] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:20,994] {logging_mixin.py:109} INFO - [2022-03-14 20:57:20,994] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:57:21,003] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:21,010] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.485 seconds
[2022-03-14 20:57:51,134] {processor.py:163} INFO - Started process (PID=9347) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:51,136] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:57:51,136] {logging_mixin.py:109} INFO - [2022-03-14 20:57:51,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:51,594] {logging_mixin.py:109} INFO - [2022-03-14 20:57:51,594] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:57:51,602] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:57:51,609] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.476 seconds
[2022-03-14 20:58:21,701] {processor.py:163} INFO - Started process (PID=9410) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:21,702] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:58:21,703] {logging_mixin.py:109} INFO - [2022-03-14 20:58:21,702] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:22,212] {logging_mixin.py:109} INFO - [2022-03-14 20:58:22,211] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:58:22,220] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:22,227] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.528 seconds
[2022-03-14 20:58:52,291] {processor.py:163} INFO - Started process (PID=9471) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:52,293] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:58:52,294] {logging_mixin.py:109} INFO - [2022-03-14 20:58:52,294] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:52,790] {logging_mixin.py:109} INFO - [2022-03-14 20:58:52,789] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:58:52,801] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:58:52,808] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.518 seconds
[2022-03-14 20:59:22,921] {processor.py:163} INFO - Started process (PID=9523) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:22,923] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:59:22,923] {logging_mixin.py:109} INFO - [2022-03-14 20:59:22,923] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:23,374] {logging_mixin.py:109} INFO - [2022-03-14 20:59:23,373] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:59:23,382] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:23,387] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.468 seconds
[2022-03-14 20:59:53,507] {processor.py:163} INFO - Started process (PID=9586) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:53,508] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 20:59:53,509] {logging_mixin.py:109} INFO - [2022-03-14 20:59:53,509] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:53,965] {logging_mixin.py:109} INFO - [2022-03-14 20:59:53,964] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 20:59:53,973] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 20:59:53,979] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.474 seconds
[2022-03-14 21:00:24,065] {processor.py:163} INFO - Started process (PID=9648) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:24,066] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:00:24,066] {logging_mixin.py:109} INFO - [2022-03-14 21:00:24,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:24,557] {logging_mixin.py:109} INFO - [2022-03-14 21:00:24,557] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:00:24,565] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:24,570] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.507 seconds
[2022-03-14 21:00:54,657] {processor.py:163} INFO - Started process (PID=9700) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:54,659] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:00:54,659] {logging_mixin.py:109} INFO - [2022-03-14 21:00:54,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:55,115] {logging_mixin.py:109} INFO - [2022-03-14 21:00:55,114] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:00:55,123] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:00:55,129] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.473 seconds
[2022-03-14 21:01:25,226] {processor.py:163} INFO - Started process (PID=9764) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:25,228] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:01:25,228] {logging_mixin.py:109} INFO - [2022-03-14 21:01:25,228] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:25,688] {logging_mixin.py:109} INFO - [2022-03-14 21:01:25,687] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:01:25,695] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:25,701] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.476 seconds
[2022-03-14 21:01:55,785] {processor.py:163} INFO - Started process (PID=9817) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:55,787] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:01:55,787] {logging_mixin.py:109} INFO - [2022-03-14 21:01:55,787] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:56,286] {logging_mixin.py:109} INFO - [2022-03-14 21:01:56,285] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:01:56,294] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:01:56,300] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.516 seconds
[2022-03-14 21:02:26,397] {processor.py:163} INFO - Started process (PID=9878) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:26,406] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:02:26,406] {logging_mixin.py:109} INFO - [2022-03-14 21:02:26,406] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:26,872] {logging_mixin.py:109} INFO - [2022-03-14 21:02:26,872] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:02:26,880] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:26,885] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.490 seconds
[2022-03-14 21:02:57,012] {processor.py:163} INFO - Started process (PID=9939) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:57,016] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:02:57,017] {logging_mixin.py:109} INFO - [2022-03-14 21:02:57,017] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:57,482] {logging_mixin.py:109} INFO - [2022-03-14 21:02:57,481] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:02:57,490] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:02:57,495] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.490 seconds
[2022-03-14 21:03:28,100] {processor.py:163} INFO - Started process (PID=9991) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:28,101] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:03:28,101] {logging_mixin.py:109} INFO - [2022-03-14 21:03:28,101] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:28,558] {logging_mixin.py:109} INFO - [2022-03-14 21:03:28,557] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:03:28,566] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:28,571] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.474 seconds
[2022-03-14 21:03:58,666] {processor.py:163} INFO - Started process (PID=10053) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:58,669] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:03:58,669] {logging_mixin.py:109} INFO - [2022-03-14 21:03:58,669] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:59,134] {logging_mixin.py:109} INFO - [2022-03-14 21:03:59,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:03:59,142] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:03:59,148] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.484 seconds
[2022-03-14 21:04:29,249] {processor.py:163} INFO - Started process (PID=10115) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:04:29,250] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:04:29,251] {logging_mixin.py:109} INFO - [2022-03-14 21:04:29,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:04:29,691] {logging_mixin.py:109} INFO - [2022-03-14 21:04:29,691] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:04:29,698] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:04:29,703] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.458 seconds
[2022-03-14 21:04:59,827] {processor.py:163} INFO - Started process (PID=10168) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:04:59,829] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:04:59,829] {logging_mixin.py:109} INFO - [2022-03-14 21:04:59,829] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:05:00,286] {logging_mixin.py:109} INFO - [2022-03-14 21:05:00,286] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:05:00,294] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:05:00,300] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.475 seconds
[2022-03-14 21:05:30,393] {processor.py:163} INFO - Started process (PID=10231) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:05:30,394] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:05:30,395] {logging_mixin.py:109} INFO - [2022-03-14 21:05:30,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:05:30,853] {logging_mixin.py:109} INFO - [2022-03-14 21:05:30,853] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:05:30,861] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:05:30,866] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.475 seconds
[2022-03-14 21:06:00,963] {processor.py:163} INFO - Started process (PID=10293) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:00,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:06:00,965] {logging_mixin.py:109} INFO - [2022-03-14 21:06:00,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:01,463] {logging_mixin.py:109} INFO - [2022-03-14 21:06:01,462] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:06:01,471] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:01,476] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.515 seconds
[2022-03-14 21:06:31,571] {processor.py:163} INFO - Started process (PID=10347) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:31,572] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:06:31,572] {logging_mixin.py:109} INFO - [2022-03-14 21:06:31,572] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:32,033] {logging_mixin.py:109} INFO - [2022-03-14 21:06:32,033] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:06:32,041] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:32,047] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.477 seconds
[2022-03-14 21:06:42,081] {processor.py:163} INFO - Started process (PID=10391) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:42,082] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:06:42,082] {logging_mixin.py:109} INFO - [2022-03-14 21:06:42,082] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:42,553] {logging_mixin.py:109} INFO - [2022-03-14 21:06:42,553] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:06:42,561] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:06:42,567] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.487 seconds
[2022-03-14 21:07:12,628] {processor.py:163} INFO - Started process (PID=10453) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:12,629] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:07:12,630] {logging_mixin.py:109} INFO - [2022-03-14 21:07:12,630] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:13,146] {logging_mixin.py:109} INFO - [2022-03-14 21:07:13,145] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:07:13,154] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:13,160] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.534 seconds
[2022-03-14 21:07:43,223] {processor.py:163} INFO - Started process (PID=10505) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:43,225] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:07:43,225] {logging_mixin.py:109} INFO - [2022-03-14 21:07:43,225] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:43,706] {logging_mixin.py:109} INFO - [2022-03-14 21:07:43,706] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:07:43,715] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:07:43,721] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.500 seconds
[2022-03-14 21:08:13,781] {processor.py:163} INFO - Started process (PID=10566) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:13,783] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:08:13,783] {logging_mixin.py:109} INFO - [2022-03-14 21:08:13,783] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:14,306] {logging_mixin.py:109} INFO - [2022-03-14 21:08:14,306] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:08:14,314] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:14,320] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.540 seconds
[2022-03-14 21:08:44,387] {processor.py:163} INFO - Started process (PID=10627) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:44,392] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:08:44,392] {logging_mixin.py:109} INFO - [2022-03-14 21:08:44,392] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:44,886] {logging_mixin.py:109} INFO - [2022-03-14 21:08:44,886] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:08:44,894] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:08:44,899] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.514 seconds
[2022-03-14 21:09:14,956] {processor.py:163} INFO - Started process (PID=10663) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:14,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:09:14,965] {logging_mixin.py:109} INFO - [2022-03-14 21:09:14,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:15,472] {logging_mixin.py:109} INFO - [2022-03-14 21:09:15,472] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:09:15,481] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:15,488] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.534 seconds
[2022-03-14 21:09:45,592] {processor.py:163} INFO - Started process (PID=10725) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:45,593] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:09:45,594] {logging_mixin.py:109} INFO - [2022-03-14 21:09:45,594] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:46,087] {logging_mixin.py:109} INFO - [2022-03-14 21:09:46,087] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:09:46,095] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:09:46,101] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.512 seconds
[2022-03-14 21:10:16,226] {processor.py:163} INFO - Started process (PID=10778) to work on /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:10:16,228] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_ingestion_dag_v02.py for tasks to queue
[2022-03-14 21:10:16,228] {logging_mixin.py:109} INFO - [2022-03-14 21:10:16,228] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:10:16,749] {logging_mixin.py:109} INFO - [2022-03-14 21:10:16,749] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_ingestion_dag_v02.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 106, in <module>
    download_dataset_task >> unzip_task >> format_to_parquet_task >> local_to_gcs_task
NameError: name 'unzip_task' is not defined
[2022-03-14 21:10:16,758] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_ingestion_dag_v02.py
[2022-03-14 21:10:16,765] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_ingestion_dag_v02.py took 0.541 seconds
