[2022-03-16 17:10:32,781] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v03.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-16 17:10:32,788] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v03.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-16 17:10:32,789] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 17:10:32,789] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-16 17:10:32,789] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 17:10:32,797] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_from_zip_task> on 2020-01-01 00:00:00+00:00
[2022-03-16 17:10:32,800] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2022-03-16 17:10:32,802] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_v03', 'extract_from_zip_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_v03.py', '--cfg-path', '/tmp/tmp49fldzl_', '--error-file', '/tmp/tmpd3ztnz01']
[2022-03-16 17:10:32,803] {standard_task_runner.py:77} INFO - Job 79: Subtask extract_from_zip_task
[2022-03-16 17:10:32,836] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_v03.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 56c17fb3521b
[2022-03-16 17:10:32,859] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-16 17:10:32,860] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1131, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1131, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
TypeError: unsupported operand type(s) for -: 'str' and 'int'
[2022-03-16 17:10:32,869] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_ingestion_dag_v03, task_id=extract_from_zip_task, execution_date=20200101T000000, start_date=20220316T171032, end_date=20220316T171032
[2022-03-16 17:10:32,878] {standard_task_runner.py:92} ERROR - Failed to execute job 79 for task extract_from_zip_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1131, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1131, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
TypeError: unsupported operand type(s) for -: 'str' and 'int'
[2022-03-16 17:10:32,894] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 17:10:32,920] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
