[2022-03-17 18:41:39,764] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat_v02.download_dataset_task manual__2022-03-17T18:41:14.282848+00:00 [queued]>
[2022-03-17 18:41:39,771] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat_v02.download_dataset_task manual__2022-03-17T18:41:14.282848+00:00 [queued]>
[2022-03-17 18:41:39,771] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 18:41:39,771] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-17 18:41:39,771] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 18:41:39,778] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-17 18:41:14.282848+00:00
[2022-03-17 18:41:39,783] {standard_task_runner.py:52} INFO - Started process 139 to run task
[2022-03-17 18:41:39,785] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_song_feat_v02', 'download_dataset_task', 'manual__2022-03-17T18:41:14.282848+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_song_feat_v02.py', '--cfg-path', '/tmp/tmpkd6otr9_', '--error-file', '/tmp/tmphhc7z3g3']
[2022-03-17 18:41:39,786] {standard_task_runner.py:77} INFO - Job 136: Subtask download_dataset_task
[2022-03-17 18:41:39,819] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_song_feat_v02.download_dataset_task manual__2022-03-17T18:41:14.282848+00:00 [running]> on host 05b31071f52d
[2022-03-17 18:41:39,852] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_song_feat_v02
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T18:41:14.282848+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-17T18:41:14.282848+00:00
[2022-03-17 18:41:39,853] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-17 18:41:39,853] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://zenodo.org/record/4904639/files/musicoset_songfeatures.zip > /opt/***/musicoset_songfeatures.zip']
[2022-03-17 18:41:39,862] {subprocess.py:85} INFO - Output:
[2022-03-17 18:41:49,869] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-03-17 18:41:49,871] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 139. PIDs of all processes in the group: [140, 141, 139]
[2022-03-17 18:41:49,871] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 139
[2022-03-17 18:41:49,871] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-17 18:41:49,871] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-03-17 18:41:49,897] {process_utils.py:70} INFO - Process psutil.Process(pid=139, status='terminated', exitcode=0, started='18:41:39') (139) terminated with exit code 0
[2022-03-17 18:41:49,897] {process_utils.py:70} INFO - Process psutil.Process(pid=140, status='terminated', started='18:41:39') (140) terminated with exit code None
[2022-03-17 18:41:49,897] {process_utils.py:70} INFO - Process psutil.Process(pid=141, status='terminated', started='18:41:39') (141) terminated with exit code None
