[2022-03-15 20:14:14,902] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.download_dataset_task scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2022-03-15 20:14:14,908] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.download_dataset_task scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2022-03-15 20:14:14,909] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 20:14:14,909] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-03-15 20:14:14,909] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 20:14:14,916] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-02-01 00:00:00+00:00
[2022-03-15 20:14:14,921] {standard_task_runner.py:52} INFO - Started process 4421 to run task
[2022-03-15 20:14:14,923] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_v02', 'download_dataset_task', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_v02.py', '--cfg-path', '/tmp/tmp_06ovcj4', '--error-file', '/tmp/tmptaeicg6t']
[2022-03-15 20:14:14,923] {standard_task_runner.py:77} INFO - Job 52: Subtask download_dataset_task
[2022-03-15 20:14:14,956] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_v02.download_dataset_task scheduled__2020-02-01T00:00:00+00:00 [running]> on host 3570d6d4f2dc
[2022-03-15 20:14:14,987] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_v02
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2022-03-15 20:14:14,987] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-15 20:14:14,988] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://www.dropbox.com/s/a1kl5e35j4o53mz/bandcamp-items-json.zip > /opt/***/bandcamp-items-json.zip']
[2022-03-15 20:14:14,997] {subprocess.py:85} INFO - Output:
[2022-03-15 20:14:50,260] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-03-15 20:14:50,261] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 4421. PIDs of all processes in the group: [4422, 4423, 4421]
[2022-03-15 20:14:50,261] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 4421
[2022-03-15 20:14:50,261] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-15 20:14:50,261] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-03-15 20:14:50,313] {process_utils.py:70} INFO - Process psutil.Process(pid=4421, status='terminated', exitcode=0, started='20:14:14') (4421) terminated with exit code 0
[2022-03-15 20:14:50,314] {process_utils.py:70} INFO - Process psutil.Process(pid=4423, status='terminated', started='20:14:14') (4423) terminated with exit code None
[2022-03-15 20:14:50,314] {process_utils.py:70} INFO - Process psutil.Process(pid=4422, status='terminated', started='20:14:14') (4422) terminated with exit code None
